### ISSUE TITLE
[QUESTION] bigram matching on strings of mixed length

### ISSUE THREAD

**Issue by Hillard28** [julioraffo/matchit#1]
Hi Julio, hope all is well!  Your program has been immensely helpful in our ongoing study.  I've been thinking of alternative implementations, particularly partial matching, and so I've begun a loose replication of your efforts in Python.  When recreating your base case of bigram matching using Jaccard similarity, I noticed my scores can often vary slightly when it comes to comparing strings of mixed lengths.

My question is, does the order of the bigrams matter, or is it only important that they are properly matched (e.g. "jo" in "john smith" vs "smith john")? If the latter, how is a case like "jojohn smith" vs "smith john" treated, where there are two of the same bigrams in one string of different length?  Can duplicate grams be matched to the same gram of another string?  I would assume no, but controlling for this seems to give me differing results.

Using my earlier example, you have the following sets of moving bigrams:
```
jo oj jo oj jn n_ _s sm mi it th
sm mi it th h_ _j jo oh hn
```

If we leave the duplicate "jo" but assume it is unmatched, then we match a total of 7 grams, over sets of length 9 and 11 grams.  That should give us 7/SQRT(9*11) or 70.35%.

If we remove the duplicate "jo" completely, then we get 7/SQRT(9*10) or 73.79%.  I see your stock algo returns a score of 73.96%, which seems like a small difference in the latter case, but I've observed a few situations where the difference is more than a few p.p.

Is there something here that I'm missing?

**Comment by julioraffo** [comment]
Hi Ryan,

Matchit does vectorial decomposition instead of rolling de grams on one
another. Hence, duplicated grams get different frequencies. In your
example, for instance, "st" gets a frequency of 2 in both strings,
reinforcing the similarity.

The numerator is then the vectorial product. While the denominator is the
square root of the product of the two vectors norms.

This whole vectorial strategy is very valuable when adding weights to the
grams.

Only the denominator affects mixed length. You can check the scoring
function to test different approaches to deal with it. The default is the
above norms' geometric mean. But you can also have the arimethic mean
(option simple). Or, the closest to your 5th case, is the minsimple option
which uses the minimum of the two norms.

I hope this helps.

J.

**Comment by Hillard28** [comment]
Thank you Julio, this was massively helpful and I'm now able to recreate the base case!  Thank you again for such a wonderful tool.
